app/app/energApp/auth.py
from flask import redirect, render_template, flash, Blueprint, request, url_for
from flask_login import login_required, logout_user, current_user, login_user
from werkzeug.security import generate_password_hash
from .forms import LoginForm, SignupForm
from .models import db, User
from . import login_manager

auth_bp = Blueprint('auth_bp', __name__,
                    template_folder='templates',
                    static_folder='static')


@auth_bp.route('/login', methods=['GET', 'POST'])
def login_page():
    """
    Interface for logging in a user.
    """
    if current_user.is_authenticated:
        return redirect(url_for('main_bp.index'))
    login_form = LoginForm(request.form)
    if request.method == 'POST':
        if login_form.validate():
            name = request.form.get('name')
            password = request.form.get('password')
            user = User.query.filter_by(name=name).first()
            if user:
                if user.check_password(password=password):
                    login_user(user)
                    next = request.args.get('next')
                    return redirect(next or url_for('main_bp.index'))
        flash('Invalid username or password')
        return redirect(url_for('auth_bp.login_page'))
    return render_template('/login.html', form=LoginForm())


@auth_bp.route('/signup', methods=['GET', 'POST'])
def signup_page():
    """
    Interface for signing up and therefore creating a user.
    """
    signup_form = SignupForm(request.form)
    if request.method == 'POST':
        if signup_form.validate():
            name = request.form.get('name')
            password = request.form.get('password')
            existing_user = User.query.filter_by(name=name).first()
            if existing_user is None:
                user = User(name=name,
                            password=generate_password_hash(password, method='sha256'))
                db.session.add(user)
                db.session.commit()
                login_user(user)
                return redirect(url_for('main_bp.index'))
            flash('A user already exists with that nickname.')
            return redirect(url_for('auth_bp.signup_page'))
    return render_template('/signup.html', form=SignupForm())


@auth_bp.route("/logout")
@login_required
def logout_page():
    """
    User log-out logic.
    """
    logout_user()
    return redirect(url_for('main_bp.index'))


@login_manager.user_loader
def load_user(user_id):
    """
    Check if user is logged-in on every page load.
    """
    if user_id is not None:
        return User.query.get(user_id)
    return None


@login_manager.unauthorized_handler
def unauthorized():
    """
    Redirect unauthorized users to Login page.
    """
    flash('You must be logged in to view that page.')
    return redirect(url_for('auth_bp.login_page'))

app/app/energApp/routes.py
import pandas as pd
from flask import render_template, Blueprint, request, json
from flask_login import login_required, current_user

from .forms import BuildingForm
from .models import db, Building
from .predict import predict_energy_consumption
from .graph import create_plot

main_bp = Blueprint('main_bp', __name__,
                    template_folder='templates',
                    static_folder='static')
prediction = None


@main_bp.route('/')
def index():
    return render_template('index.html')


@main_bp.route('/predictions')
@login_required
def predictions_page():
    global prediction
    building_query = Building.query.filter_by(user_id=current_user.id)
    buildings = pd.read_sql(building_query.statement, building_query.session.bind)
    plots = []

    if len(buildings) > 0:
        prediction = predict_energy_consumption(buildings)
        for _, g in prediction.groupby("building_id"):
            plots.append(create_plot([1, 1, 1, 1, 1], g))

    return render_template('predictions.html',
                           buildings=buildings,
                           plots=plots)


@main_bp.route('/faq')
def faq_page():
    return render_template('faq.html')


@main_bp.route('/plot', methods=['GET', 'POST'])
def change_meters():
    """
    Responds to a ajax call which lets the user change the displayed elements
    of the graph.
    """
    prediction_building = prediction.loc[prediction["building_id"] == int(request.args["building"])]

    meter0 = int(request.args["m0"])
    meter1 = int(request.args["m1"])
    meter2 = int(request.args["m2"])
    meter3 = int(request.args["m3"])
    air_temperature = int(request.args["at"])
    return create_plot([meter0, meter1, meter2, meter3, air_temperature], prediction_building)


@main_bp.route('/buildings', methods=['GET', 'POST'])
@login_required
def buildings_page():
    """
    Displays the buildings in the current user account. Further a new building
    can be created via POST request.
    """
    building_form = BuildingForm(request.form)
    if request.method == 'POST':
        if building_form.validate():
            building = Building(name=request.form.get('name'),
                                primary_use=request.form.get('primary_use'),
                                square_feet=request.form.get('square_feet'),
                                year_built=request.form.get('year_built'),
                                floorcount=request.form.get('floorcount'),
                                latitude=request.form.get('latitude'),
                                longitude=request.form.get('longitude'),
                                user_id=current_user.id)
            db.session.add(building)
            db.session.commit()

    buildings = Building.query.filter_by(user_id=current_user.id).all()
    return render_template('building.html', buildings=buildings, form=BuildingForm())


@main_bp.route('/delete_building', methods=['GET', 'POST'])
def delete_building():
    """
    Responds to an ajax call which deletes a building from the database.
    """
    building = int(request.args["building"])
    db.session.query(Building).filter(Building.id == building).delete()
    db.session.commit()
    success = json.dumps({'success': True}), 200, {'ContentType': 'application/json'}
    return success

app/app/energApp/templates/building.html
{% extends "layout.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block body %}
<div class="container" style="padding: 10px">
    <div class="row">
        <div class="col-sm-6">
            <p><b>{{current_user.name}}'s Buildings:</b></p>
        </div>
        <div class="col-sm-6 text-right">
            <button type="button" class="btn btn-success" data-toggle="modal" data-target="#buildingModal">
                <b>+</b> Add
            </button>
        </div>
    </div>
</div>
{% for b in buildings %}
<div class="col-lg-12 card", style="padding: 10px; margin-bottom: 10px">
    <p style="text-align: left"><strong>{{ b.name}}</strong>
        <input type="button"  class="btn btn-secondary building-id" value="Delete" data-bid="{{ b.id }}" data-toggle="modal" data-target="#deleteModal" style="float: right;margin-left:8px;">
    </p>
    <hr/>
    <table class ="table table-hover" style="width: 161px;">
    <tbody>
        <tr>
        <td style="width: 82px;">
        <p><strong>Use</strong></p>
        <p>[{{b.primary_use}}]</p>
        </td>
        <td style="width: 82px;">
            <p style="text-align: end;"><strong>Floors</strong></p>
        <p style="text-align: end;">{{b.floorcount}}</p>
        </td>
        </tr>
        <tr>
        <td style="width: 82px;">
        <p><strong>Size</strong></p>
        <p>{{b.square_feet}} sq ft</p>
        </td>
        <td style="width: 82px;">
            <p style="text-align: end;"><strong>Year</strong></p>
            <p style="text-align: end;">{{b.year_built}}</p>
        </td>
        </tr>
    </tbody>
    </table>
</div>
<hr style="height:1px;border:none;background-color:darkgreen;"/>
{% endfor %}

<!-- Modal -->
<div class="modal fade" id="buildingModal" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered mw-100 w-75">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Please enter building details</h5>
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container" style="padding: 10px">
            <div class="row">
                <div class="col-sm-8 border rounded", style="padding: 10px">
                    <div id="mapid"></div>
                </div>
                <div class="col-sm-4">
                    {{ wtf.quick_form(form, button_map={'submit':'success text-right'}) }}
                </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Delete -->
<div class="modal fade" id="deleteModal" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered mw-100 w-75">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Are you sure you want to delete this building?</h5>
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container" style="padding: 10px">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Abort</button>
        <button type="button" class="btn btn-success delete-building" data-dismiss="modal">Delete Building</button>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>


<script src="{{ url_for('static', filename='building_map.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>


{% endblock %}

app/app/energApp/templates/faq.html
{% extends "layout.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block body %}
<div class="col-lg-12 text-center" style="margin: 10px">
  <h3>Frequently Asked Questions</h3>
</div>
<div class="container card">
  <button type="button" class="collapsible" style="margin-top: 10px;">
    <strong>Who are the EnerGeeks?</strong>
  </button>
  <div class="row align-items-center coll-content" id="coll-0">
    <div class="col-sm-12 text-left" id="faq0" style="margin: 5px">
      <p>We are computer science & statistics students at LMU Munich and this project is happening as part of a Data Science Practical. Our plan was to participate in the associated Kaggle Challenge and subsequently build a product surrounding the trained model. Eventually we placed 160th in the public leaderboard and unfortunately only 509th in the private leaderboard.</p>
    </div>
  </div>

  <button type="button" class="collapsible" style="margin-top: 10px;">
    <strong>What is the EnergApp?</strong>
  </button>
  <div class="row align-items-center coll-content" id="coll-1">
    <div class="col-sm-12 text-left" id="faq1" style="margin: 5px">
      <p>EnergApp is the second phase of our data science practical. The aim of EnergApp is to incorporate the predicted model from the kaggle challenge. The idea behind this is that you can submit your building's data and in return get the predicted energy consumption for said building, which makes our findings available to everyone.</p>
    </div>
  </div>

  <button type="button" class="collapsible" style="margin-top: 10px;">
    <strong>Do I need to sign up?</strong>
  </button>
  <div class="row align-items-center coll-content" id="coll-2">
    <div class="col-sm-12 text-left" id="faq2" style="margin: 5px">
      <p>Yes, in order to submit and manage your buildings, you have to sign up for our web application. Don't worry, your data will be safe with us</p>
    </div>
  </div>

  <button type="button" class="collapsible" style="margin-top: 10px;">
    <strong>Where can I manage my buildings?</strong>
  </button>
  <div class="row align-items-center coll-content" id="coll-3">
    <div class="col-sm-12 text-left" id="faq3" style="margin: 5px">
      <p>Use the navbar to go to the buildings section or click <a href="{{url_for('main_bp.buildings_page')}}">here</a>. You'll find a list of all your buildings and accompanying attributes.</p>
    </div>
  </div>

  <button type="button" class="collapsible" style="margin-top: 10px;">
    <strong>How can I submit my building's data?</strong>
  </button>
  <div class="row align-items-center coll-content" id="coll-4">
    <div class="col-sm-12 text-left" id="faq4" style="margin: 5px">
      <p>In the buildings tab just click on the <b>ADD+</b> button and enter your building's details.</p>
    </div>
  </div>


  <button type="button" class="collapsible" style="margin-top: 10px;">
    <strong>Where do I find the predictions?</strong>
  </button>
  <div class="row align-items-center coll-content" id="coll-11">
    <div class="col-sm-12 text-left" id="faq11" style="margin: 5px">
      <p>Just go to the <a href="{{url_for('main_bp.predictions_page')}}">prediction tab</a> and enjoy.</p>
    </div>
  </div>

  <button type="button" class="collapsible" style="margin-top: 10px;">
    <strong>What model is used for the predictions?</strong>
  </button>
  <div class="row align-items-center coll-content" id="coll-5">
    <div class="col-sm-12 text-left" id="faq5" style="margin: 5px">
      <p> We trained our model by using LightGBM, which is common framework for gradient boosting.</p>
    </div>
  </div>

  <button type="button" class="collapsible" style="margin-top: 10px;">
    <strong>Can I trust the predictions?</strong>
  </button>
  <div class="row align-items-center coll-content" id="coll-6">
    <div class="col-sm-12 text-left" id="faq6" style="margin: 5px">
      <p>Well yes, but actually no. We tried to make the predictions as accurate as possible but forecasting the energy consumption for unseen buildings is still very experimental and needs further evaluation to be stable.</p>
    </div>
  </div>

  <button type="button" class="collapsible" style="margin-top: 10px;">
    <strong>Can I download the model somewhere?</strong>
  </button>
  <div class="row align-items-center coll-content" id="coll-7">
    <div class="col-sm-12 text-left" id="faq7" style="margin: 5px">
      <p>We provide our model in txt-format, which can be downloaded from <a href="https://syncandshare.lrz.de/getlink/fiEpYXwqbwsQjuBHaJ1ZRNnF/model-lgbm-gbdt-600-no-ids.txt">here</a></p>
    </div>
  </div>

  <button type="button" class="collapsible" style="margin-top: 10px;">
    <strong>Can I access your model without your app?</strong>
  </button>
  <div class="row align-items-center coll-content" id="coll-8">
    <div class="col-sm-12 text-left" id="faq8" style="margin: 5px">
      <p>Sure, we provide a public endpoint, which will return your predictions if you provide the necessary inpute data. The endpoint is "localhost:5001/predict".</p>
    </div>
  </div>

  <button type="button" class="collapsible" style="margin-top: 10px;">
    <strong>What input is required for Model API?</strong>
  </button>
  <div class="row align-items-center coll-content" id="coll-9">
    <div class="col-sm-12 text-left" id="faq9" style="margin: 5px">
      <p> We provide a list of all required attributes as well as an example request, which can be found in our <a href="https://github.com/energeeks/ashrae-energy-prediction">repository</a>.
      </p>
    </div>
  </div>

  <button type="button" class="collapsible" style="margin-top: 10px;">
    <strong>I really like it here, what can I do for you?</strong>
  </button>
  <div class="row align-items-center coll-content" id="coll-10">
    <div class="col-sm-12 text-left" id="faq10" style="margin: 5px">
      <p>Thanks for the compliment! We really appreciate it, since we invested a lot of time and effort to create this amazing project. If by chance you are our supervisor, we would be really happy to receive a good grade ;)</p>
    </div>
  </div>
</div>

<script src="{{ url_for('static', filename='faq.js') }}"></script>

{% endblock %}

app/app/energApp/templates/index.html
{% extends "layout.html" %}
{% block body %}
<div class="container text-center" style="margin: 20px">
    <div class="col-lg-12">
        <p><strong><i>Get your energy forecast today!</strong></i></p>
        <p>
            The EnergApp predicts the energy consumption of <i>your</i> buildings for the coming week!
            Don't get surprised anymore and start your adventure by <a href={{url_for('auth_bp.signup_page')}}>registering</a>
            or <a href={{url_for('auth_bp.login_page')}}>logging in</a>. Then add your <a href={{url_for('main_bp.buildings_page')}}>buildings</a> and
            enjoy your <a href={{url_for('main_bp.predictions_page')}}>predictions</a>.
        </p>
    </div>
</div>
<hr>
<div class="container text-center" style="margin: 20px">
  <div class="row">
    <div class="col-sm-4">
        <div class="col-sm-12 card text-center">
            <a href={{url_for('main_bp.faq_page')}}>
                <img src="{{ url_for('static', filename='images/faq-tile.png') }}" class="resize" alt="faq">
            </a>
            <hr>
            <p><strong>Check the FAQs!</strong></p>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="col-sm-12 card text-center">
          <a href="https://github.com/energeeks/ashrae-energy-prediction">
              <img src="{{ url_for('static', filename='images/git-tile.png') }}" class="resize" alt="faq">
          </a>
            <hr>
            <p><strong>Check EnerGeeks at Github!</strong></p>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="col-sm-12 card text-center">
            <a href="">
                <img src="{{ url_for('static', filename='images/discord_logo.png') }}" class="resize" alt="faq">
            </a>
            <hr>
            <p><strong>Get in touch!</strong></p>
        </div>
    </div>
  </div>
</div>
<hr>
<div class="container text-center" style="margin: 20px">
    <div class="row" style="margin: 1em;">
        <div class="col-sm-12 card" style="max-width: 600px">
            <table class ="table">
                <thead>
                <p><i>A Project by:</i></p>
                </thead>
                <tbody>
                    <tr>
                        <td style="width: 40px; vertical-align: middle">
                            <img src="{{ url_for('static', filename='images/Adrian_avatar.png') }}" alt="Avatar" class="avatar">
                        </td>
                        <td style="width: 82px; vertical-align: middle;text-align:left">
                            <p style="text-align: left;">Adrian</p>
                        </td>
                        <td style="width: 40px; vertical-align: middle">
                            <img src="{{ url_for('static', filename='images/Dario_avatar.png') }}" alt="Avatar" class="avatar">
                        </td>
                        <td style="width: 82px; vertical-align: middle">
                            <p style="text-align: left;">Dario</p>
                        </td>
                    </tr>
                    <tr>
                        <td style="width: 40px; vertical-align: middle">
                            <img src="{{ url_for('static', filename='images/Erjona_avatar.png') }}" alt="Avatar" class="avatar">
                        </td>
                        <td style="width: 82px; vertical-align: middle;text-align:left">
                            <p style="text-align: left;">Erjona</p>
                        </td>
                        <td style="width: 40px; vertical-align: middle">
                            <img src="{{ url_for('static', filename='images/Tobias_avatar.png') }}" alt="Avatar" class="avatar">
                        </td>
                        <td style="width: 82px; vertical-align: middle">
                            <p style="text-align: left;">Tobias</p>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<hr>
<div class="col-lg-12 text-center">
      <div id="openweathermap-widget-22" style="margin: 0 auto;display: table"></div>
        <script>
            window.myWidgetParam ? window.myWidgetParam : window.myWidgetParam = [];
            window.myWidgetParam.push({id: 22,
                cityid: '2867714',
                appid: '{{ config.API_KEY }}',
                units: 'metric',
                containerid: 'openweathermap-widget-22'});
            (function() {
                var script = document.createElement('script');
                script.async = true;
                script.charset = "utf-8";
                script.src = "//openweathermap.org/themes/openweathermap/assets/vendor/owm/js/weather-widget-generator.js";
                var s = document.getElementsByTagName('script')[0];
                s.parentNode.insertBefore(script, s);  })();
        </script>
</div>
{% endblock %}

app/app/energApp/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>EnergApp</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">

    <!-- Bootstrap core components -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    <!-- Leaflet components -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
      integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
      crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"
      integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew=="
      crossorigin=""></script>

       <!-- CSS and JS files for Search Box -->
    <script src="https://cdn-geoweb.s3.amazonaws.com/esri-leaflet/0.0.1-beta.5/esri-leaflet.js"></script>
    <script src="https://cdn-geoweb.s3.amazonaws.com/esri-leaflet-geocoder/0.0.1-beta.5/esri-leaflet-geocoder.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn-geoweb.s3.amazonaws.com/esri-leaflet-geocoder/0.0.1-beta.5/esri-leaflet-geocoder.css">

    <!-- Plotly and D3 JS -->
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js"></script>

    <!-- Local components -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">

</head>
<body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light static-top">
        <div class="container">
            <a class="navbar-brand" href={{url_for('main_bp.index')}}>
                <img src="{{url_for('static', filename='images/energeek_logo.png')}}" width="30" height="30" class="d-inline-block align-top" alt="">
                EnergApp
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href={{url_for('main_bp.predictions_page')}}>Predictions
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href={{url_for('main_bp.buildings_page')}}>Buildings</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href={{url_for('main_bp.faq_page')}}>FAQs</a>
                    </li>
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href={{url_for('auth_bp.logout_page')}}><b>Log Out</b></a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href={{url_for('auth_bp.login_page')}}><b>Log In</b></a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

  <!-- Page Content -->
    <div class="container">
        {% block body %}{% endblock %}
    </div>

</body>

</html>

app/app/energApp/templates/login.html
{% extends "layout.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block body %}
<div class="container border rounded" style="max-width: 400px; margin-top: 5em;" >
  <div class = "center-block" style="padding: 10px">
        {% for message in get_flashed_messages() %}
      <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          {{ message }}
      </div>
    {% endfor %}
    <div class="logo text-center">
      <img src="{{url_for('static', filename='images/energeek_logo.png')}}" width="30" height="30">
      <h2>Login</h2>
    </div>
    <hr>
    {{ wtf.quick_form(form, button_map={'submit':'success'}) }}    <hr>
    <div>
      <span>Don't have an account? <a href="{{ url_for('auth_bp.signup_page') }}">Sign up.</a></span>
    </div>
</div>
</div>


{% endblock %}

app/app/energApp/templates/predictions.html
{% extends "layout.html" %}

{% block body %}
<div class="container">
  {% for i, b in buildings.iterrows() %}
    <button type="button" class="collapsible" style="margin-top: 10px;">{{ b["name"] }}</button>
    <div class="row align-items-center coll-content" id="coll-{{ i }}">
      <div class="col-sm-10" id="building{{ i }}">
        <script>
          var plot = {{ plots[i] | safe }};
          var graphs = plot.data;
          var layout = plot.layout;
          Plotly.plot("building{{i}}",graphs, layout);
        </script>
      </div>
      <div class="col-sm-2 meter-types" id="meter-types-{{ i }}" data-building ="{{ b["id"] }}" data-index="{{i}}" style="margin-top: 5px">
        <h6>Meters:</h6>
        <hr>
        <div class="checkbox">
          <label><input id="b{{ i }}-m0" type="checkbox" value="" checked>Electricity</label>
        </div>
        <div class="checkbox">
          <label><input id="b{{ i }}-m1" type="checkbox" value="" checked>Chilled Water</label>
        </div>
        <div class="checkbox">
          <label><input id="b{{ i }}-m2" type="checkbox" value="" checked>Steam</label>
        </div>
        <div class="checkbox">
          <label><input id="b{{ i }}-m3" type="checkbox" value="" checked>Hot Water</label>
        </div>
        <hr>
        <div class="checkbox">
          <label><input id="b{{ i }}-at" type="checkbox" value="" checked>Air Temperature</label>
        </div>
        <hr>
      </div>
    </div>
  {% endfor %}
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="{{ url_for('static', filename='plots.js') }}"></script>
<script src="{{ url_for('static', filename='predictions.js') }}"></script>
{% endblock %}

app/app/energApp/templates/signup.html
{% extends "layout.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block body %}
<div class="container border rounded" style="max-width: 400px">
  <div class = "center-block" style="padding: 10px">
        {% for message in get_flashed_messages() %}
      <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          {{ message }}
      </div>
    {% endfor %}
    <div class="logo text-center">
      <img src="{{url_for('static', filename='images/energeek_logo.png')}}" width="30" height="30">
      <h2>Sign Up</h2>
    </div>
    <hr>
    {{ wtf.quick_form(form, button_map={'submit':'success'}) }}    <hr>
    <div>
      <span>Already have an account? <a href="{{ url_for('auth_bp.login_page') }}">Log in.</a></span>
    </div>
  </div>
</div>

{% endblock %}

app/app/energApp/templates/something.html
{% extends "layout.html" %}

{% block body %}
  <div class="col-lg-12 text-center">
    <h1>Routing works!</h1>
  </div>
{% endblock %}